name: Dev Build

on:
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew clean setupCrucible

    - name: Create distribution
      run: ./gradlew jar
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.sha }}
        prerelease: true
        name: Dev build ${{ github.sha }}
        files: |
          build/distributions/libraries.zip
          build/distributions/*-server.jar
